language: node_js
node_js:
- '10'
env:
  matrix:
    secure: JrSOiIiagrPzUwjyzNuoY/GIxMrMerKIKqTtI06kXt5SDSaYEDWTBDnh1F9PzgyBN8kTw26YYlGc3lNSbblDWVTkJpZPjYC8Mk8cPOSK/UoOBXZIZc90v3ifUn9UR0JqnYA6KNdtQxsA//AqZ+vBKr7n0UF+Y9WJzfmgolTA1389x64MhZueQnvSf4H9dxQaZiyEizLPOEyzyQUkuglT1VFiCV6Ct+OXrljpPQyJIx47g1LSVnoojeq3WgB/GOnu1ui3TDd+/JhQjuACJ4fxoG/7hwt3hy1xpVb6+kYk7FindnShUv1xup1fXecZiGAlMBrKwZ3Fyd7/q4kG2FbAjarfq13/f19Ewo6NzHAZFxEPSTsgHSYN9ODDhJQ328LQ9Kydt0I5FQ0CTDUwpBv/Sz471vvPwloO6R1+m6up3SPS0arljFYF66C6jOkhDDgZzzGIXeleeqZdvHmOp1C4lYH4DQdi7YoZnZA4aQNXkdzHHzyTbPfk9LljZRyvHZIdk1OvQfLXBY8FctGtxRHQJg34WaepOg0mQsz1e0Y12wuqJMlS3xcaUEZ2hSqqy36e2GbZUgt8HkV/zhbEJq15TSfYZaSGIoxOBSNM1JA/NTlrw8W4FTkJokH1KDi55OCjQOkOY/iOXSXnsvqtFbBY2OKa5Gi70Iu+g0J4R7Wz0Z0=
